### ISSUE TITLE
Remove duplicate information from altLabels and texts

### ISSUE THREAD

**Issue by ioggstream** [par-tec/esco-playground#26]
## I expect

- [ ] to have a comprehensive test case for matched skills (e.g., a text string together with a set of associated skills that should be extracted)

## Instead

- we do not have it

**Comment by masciotta02** [comment]
#spacy matcher knowledges 

import spacy
import spacy.matcher import Matcher

nlp = spacy.load("en_core_web_sm")

matcher = Matcher(nlp.vocab)

#I define one pattern but there can be many other... (refer to database administrator (knowledge found on esco))
patterns = [{"pattern":[{"LOWER":"data"},{"LOWER":"models"}]},
		{"pattern":[{"LOWER":"data"},{"LOWER":"storage"}]},
		{"pattern":[{"LOWER":"information"},{"LOWER":"struction"}]},
		{"pattern":[{"LOWER":"database"},{"LOWER":"management"},{"LOWER":"systems"}]},
]
#obviusly there are other knowledge for this job position...

for p in patterns:
	matcher.add("DBA_PATTERN",[p["pattern"]])

def _identifies_kledge(text):
	doc = nlp(text)
	matches = matcher(doc)
	kledge = [doc[start:end].text for match_id, start, end in matches]
	return set(kledge)

#example: if we have a CV and are interested in looking for a particular position,
#		we can use this method to quickly view the candidate's essential knowledge

text = "I possess a diverse set of technical skills essential for a Database Administrator, including:
	Proficiency in SQL and experience with database management systems such as MySQL, PostgreSQL, and MongoDB.
	Familiarity with database design principles and normalization techniques.
	Knowledge of scripting languages like Python for automating database tasks.
	Understanding of data backup and recovery strategies.
	Basic knowledge of cloud-based database services (e.g., AWS RDS, Google Cloud SQL)."
print(_identifies_kledge(text))

#I think it would also better to include optional knowledge, because as I have also seen from Esco, 
they are the most frequently used words in CVs, perhaps by doing a search only on essential knowledge 
we risk missing something...

**Comment by ioggstream** [comment]
Test cases could be something like

```
- skills:
  - label: have computer literacy
    score: 0.36953122123143567
    uri: http://data.europa.eu/esco/skill/d15ce60f-ddab-41ce-ba56-398451b77b60
  - label: perform ICT security testing
    score: 0.364592705125277
    uri: http://data.europa.eu/esco/skill/f4a85869-1855-45d5-a43c-7ee8cd451996
  - label: identify digital competence gaps
    score: 0.35520025378575937
    uri: http://data.europa.eu/esco/skill/238343b1-7b51-42b3-a9ed-cf24d3a236e7
  - label: manage system security
    score: 0.35375058521861025
    uri: http://data.europa.eu/esco/skill/2a3a96a3-709e-4d60-81f6-d247d6933f13
  - label: teach digital literacy
    score: 0.31787485634121276
    uri: http://data.europa.eu/esco/skill/c8fa4313-80b0-4f37-8b1b-1739707bc362
  - label: maintain database security
    score: 0.3150766023526833
    uri: http://data.europa.eu/esco/skill/ec85cc63-4e24-4631-bf92-8789db2605c0
  - label: utilise machine learning
    score: 0.3074994060943626
    uri: http://data.europa.eu/esco/skill/8369c2d6-c100-4cf6-bd83-9668d8678433
  text: "My strong point is bugfixing\n \n \nTRAINING AND EDUCATION\n \n\uF0B7 2002:\
    \ Telecommunications Technician High School Diploma\nat the IPSIA  institute\
    \ in Milan\n \n\uF0B7 2015: Three-year degree in Computer Engineering at the\
    \ University of Pesaro with\nrating of 80/110\nDuring my university studies I\
    \ created software for sending encrypted emails based on\nelliptic curves using\
    \ the .NET platform, with the C# language and Windows Forms."
```
